import { Link } from 'react-router-dom';
import { Container, Eyebrow, Section } from '../components/ui';
import { Seo } from '../components/Seo';
import { QuickLeadSection } from '../features/quickLead/QuickLeadSection';
import { Faq as FaqAccordion } from '../components/sections';
import { breadcrumbSchema, faqSchema } from '../lib/structuredData';

const questions=[['Comment débute l’étude d’un projet ?','Un premier échange permet de comprendre le site, les équipements concernés et les enjeux d’exploitation avant de définir les informations utiles à l’analyse.'],['Quels bâtiments et sites sont concernés ?','Le site s’adresse aux bâtiments professionnels, aux sites industriels, logistiques, commerciaux, agroalimentaires, tertiaires et de santé.'],['Quelles informations préparer avant un premier échange ?','Les usages, équipements, contraintes d’exploitation et documents déjà disponibles peuvent aider à cadrer la discussion.'],['Peut-on intervenir sur un site en activité ?','Les conditions d’intervention sont étudiées avec la continuité d’usage attendue et le périmètre technique concerné.'],['Comment sont étudiés les financements et les CEE ?','Les dispositifs éventuels sont examinés selon l’opération, le site et les conditions applicables, sans promesse préalable.'],['Une opération est-elle automatiquement éligible ?','Non. L’éligibilité dépend du projet et doit être vérifiée avant tout engagement.'],['Peut-on étudier plusieurs équipements sur un même site ?','Oui. Les interactions entre les équipements peuvent justement être utiles pour hiérarchiser les priorités.'],['Comment se déroule la prise de contact ?','Vous pouvez présenter votre contexte via le formulaire ; un premier échange permet ensuite de préciser le besoin.']];
export default function Faq(){return <><Seo title="FAQ performance énergétique des entreprises" description="Audit, travaux, CEE, financement et équipements : réponses aux questions fréquentes pour préparer un projet de performance énergétique professionnel." canonicalPath="/faq" schema={[faqSchema(questions),breadcrumbSchema([{name:'Accueil',path:'/'},{name:'FAQ',path:'/faq'}])]}/><Section><Container><div className="faq-layout"><div><Eyebrow>Questions fréquentes</Eyebrow><h1>Préparer un projet de performance énergétique.</h1><p className="lead small">Des réponses claires sur l’étude énergétique, les travaux, les équipements et les financements possibles pour un site professionnel.</p><Link className="text-link" to="/contact">Parler de votre projet</Link></div><FaqAccordion subject="votre projet" items={questions}/></div></Container></Section><QuickLeadSection variant="generic"/></>}
